fix: downgrade mongodb to 4.17.1 (CR-25053)
codefresh-io/service-base pull request #161
Opened 2024-08-25 11:53 UTC by kim-codefresh

2024-09-08 14:08 UTC, masontikhonov commented on infra/mongo.js
> +        logger.info(`Mongo db uri ${uri}`);
I assume we shouldn't log URI because of possible credentials leak to logs.

2024-09-08 14:12 UTC, masontikhonov requested changes
Let's remove URI logging as it can cause credentials leak.

2024-09-09 07:22 UTC, masontikhonov commented on package.json
> +  "version": "6.0.2-beta",
```suggestion
  "version": "7.0.0",
```
I suggest bumping major version since exported mongoclient has breaking changes.

2024-09-10 05:32 UTC, kim-codefresh commented on package.json
> +  "version": "6.0.2-beta",
yeah sure this is temporary, I will change before merging

2024-09-16 13:52 UTC, masontikhonov commented on infra/mongo.js
> +    async stop() {
@kim-codefresh I just realized that this can be more straightforward; IDK why we're checking `this.db`.
```suggestion
    async stop() {
      await this.client?.close();
    }
```

2024-10-08 17:05 UTC, masontikhonov commented on infra/mongo.js
> +    async stop() {
Actually no, conditional chaining (`?.` syntax) is a native JS feature, so we can safely replace as in my first comment

2024-10-08 17:05 UTC, masontikhonov approved these changes

2024-10-09 07:18 UTC, kim-codefresh commented on infra/mongo.js
> +    async stop() {
yeah sorry the issue is that our linter not allowing it

2024-10-10 05:14 UTC, merged